### ISSUE TITLE
check_issue HttpError: Label does not exist

### ISSUE THREAD

**Issue by kostecky** [stevenzeck/issue-checker#135]
Hello. When I run this action, I'm receiving a `HttpError: Label does not exist`. The label certainly exists. I'm curious if this should work on private repos or if you have an idea of where this error may be coming from? Thanks!

**Comment by stevenzeck** [comment]
Hey @kostecky. It's been a while since I actually tried this in a real repository. Let me look into.

**Comment by kostecky** [comment]
No worries. Just FYI. I found another way of accomplishing this using https://github.com/marketplace/actions/issues-helper and searching the issue body for "[ ]". This basically accomplishes what I need and I can follow up with other actions.

Thank you for responding so quickly though!

**Comment by stevenzeck** [comment]
I guess I never hit the Comment button after writing last night. Glad to hear you found an alternative.

It's ultimately caused by the [`octokit.rest.issues.removeLabel`](https://github.com/stevenzeck/issue-checker/blob/7a67531c7eebf7707c7631ba0a37d7b826bc13f2/src/main.ts#L104) call. When there is no label to remove, the action completely fails. They must have changed something, because it didn't used to behave like that.
